name = "GraknClient"
uuid = "7ffdda62-db04-4838-9798-febd00f3125c"
authors = ["Humans of Julia"]
version = "0.1.0"

[deps]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
