name: CI
on:
  - push
#   - pull_request


jobs:

  changelog:
    name: CHANGELOG
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
    - uses: actions/checkout@v1

    - name: Check that CHANGELOG has been updated (deactivated for now)
      run: |
        # If this step fails, this means you haven't updated the CHANGELOG.md
        # file with notes on your contribution.
        # git diff --name-only $(git merge-base origin/master HEAD) | grep '^CHANGELOG.md$' && echo "Thanks for helping keep our CHANGELOG up-to-date!"
  test:
    name: Julia ${{ matrix.version }} - Python ${{ matrix.python }}
      ${{ matrix.os }} ${{ matrix.architecture }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.5'
          - 'nightly'
        python: [3.7]
        
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        arch:
          - x64

#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up 🐍 ${{ matrix.python }}
#        uses: actions/setup-python@v2
#        with:
#          python-version: ${{ matrix.python }}
#
#      - name: Display Python version
#        run: python -c "import sys; print(sys.version)"
#            
#      - name: Set ENV Variables for 🐍 📞
#        run: |
#          echo ENV["PYTHON"] = python >> $GITHUB_ENV
#
#      - name: Install dependencies 🔧
#        run: |
#          python -m pip install --upgrade pip
#          pip install -r requirements.txt
#      
#
#      - name: Get pip cache dir
#        id: pip-cache
#        run: |
#          echo "::set-output name=dir::$(pip cache dir)"
#    
#      - uses: actions/cache@v2
#        with:
#          path: ${{ env.pythonLocation }}
#          key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}

      # Julia Tasks test
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
        
      - uses: actions/cache@v2
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      
      - uses: julia-actions/julia-buildpkg@v1
        env:
          PYTHON : python
            
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info

  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up 🐍 
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Set ENV Variables for 🐍 📞
        run: |
          echo ENV["PYTHON"] = python >> $GITHUB_ENV
         

      - name: Install dependencies 🔧
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - uses: julia-actions/setup-julia@v1
        env:
            PYTHON : python
        with:
          version: '1'
      - run: |
          julia --project=docs -e '
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()'
      - run: |
          julia --project=docs -e '
            using Documenter: doctest
            using GraknClient
            doctest(GraknClient)'
      - run: julia --project=docs docs/make.jl
        env:          
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
