
name: Graction
on: [push]
jobs:
  test:
    runs-on: [ubuntu-18.04]
    steps:
      - name: remote-bash
        uses = "lafernando/github-action-bash/@master"
        with:
          args: arg1 arg2
          env:
            REMOTE_BASH_URL: https://github.com/Humans-of-Julia/GraknClient.jl/blob/BDD-infrastructure/test/runbdd.sh